version: "3.8"
services:
  api:
    build: ./api
    container_name: app_c
    ports:
      - "5000:4000"
    volumes:
      - ./api:/app
      - ./app/node_modules
      - C:\development\docker_netninja\api\node_modules:/app/node_modules

